server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      force-response: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/  #? ???? ??? ?? ?????? /WEB-INF/views/? ????
      suffix: .jsp  #? ?? ?? ?? ???? .jsp? ????

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cupick?serverTimezone=Asia/Seoul
    username: jang   #???????? ?????? cos???
    password: 8941  #?????? ?? ????? cos1234? ??

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update   #??????? ???? ?? update? ?????
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

테스트